name: Deploy to Server

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Node.js environment
           uses: actions/setup-node@v2
           with:
              node-version: '22'

         - name: Create SSH directory
           run: mkdir -p ~/.ssh
         - name: Create authorized_keys file
           run: touch ~/.ssh/authorized_keys
         - name: Set permissions
           run: chmod 600 ~/.ssh/authorized_keys
       
         - name: Install dependencies
           run: yarn


         - name: Deploy to Server
           env:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
           run: |
              ssh -p 24700 $SSH_USERNAME@$SSH_HOST "cd /snap/dev-server/travel-app-api && pm2 restart server"
